import { ITEM_STATE } from "../shared/constants.js";

const ALLOWED = new Map([
  [ITEM_STATE.PENDING, [ITEM_STATE.RESOLVING, ITEM_STATE.ABANDONED, ITEM_STATE.FAILED]],
  [ITEM_STATE.RESOLVING, [ITEM_STATE.CANDIDATE_REGISTERED, ITEM_STATE.PDF_RESPONSE_VERIFIED, ITEM_STATE.LOGIN_REQUIRED, ITEM_STATE.MANUAL_REQUIRED, ITEM_STATE.NO_ENTITLEMENT, ITEM_STATE.BLOCKED, ITEM_STATE.FAILED]],
  [ITEM_STATE.CANDIDATE_REGISTERED, [ITEM_STATE.RESOLVING, ITEM_STATE.PDF_RESPONSE_VERIFIED, ITEM_STATE.CACHING, ITEM_STATE.AUTHORIZED, ITEM_STATE.LOGIN_REQUIRED, ITEM_STATE.MANUAL_REQUIRED, ITEM_STATE.NO_ENTITLEMENT, ITEM_STATE.BLOCKED, ITEM_STATE.ABANDONED, ITEM_STATE.FAILED]],
  [ITEM_STATE.PDF_RESPONSE_VERIFIED, [ITEM_STATE.RESOLVING, ITEM_STATE.CACHING, ITEM_STATE.AUTHORIZED, ITEM_STATE.LOGIN_REQUIRED, ITEM_STATE.MANUAL_REQUIRED, ITEM_STATE.BLOCKED, ITEM_STATE.ABANDONED, ITEM_STATE.FAILED]],
  [ITEM_STATE.CACHING, [ITEM_STATE.VERIFYING, ITEM_STATE.INVALID_RESPONSE, ITEM_STATE.BLOCKED, ITEM_STATE.FAILED]],
  [ITEM_STATE.PDF_CACHED, [ITEM_STATE.ARCHIVING, ITEM_STATE.ABANDONED, ITEM_STATE.FAILED]],
  [ITEM_STATE.ARCHIVING, [ITEM_STATE.PDF_CACHED, ITEM_STATE.COMPLETED, ITEM_STATE.INVALID_RESPONSE, ITEM_STATE.VERIFICATION_INCONCLUSIVE, ITEM_STATE.QUARANTINED, ITEM_STATE.FAILED]],
  [ITEM_STATE.AUTHORIZED, [ITEM_STATE.CACHING, ITEM_STATE.QUEUED, ITEM_STATE.RESOLVING, ITEM_STATE.ABANDONED, ITEM_STATE.FAILED]],
  [ITEM_STATE.QUEUED, [ITEM_STATE.CACHING, ITEM_STATE.DOWNLOADING, ITEM_STATE.BLOCKED, ITEM_STATE.FAILED]],
  [ITEM_STATE.DOWNLOADING, [ITEM_STATE.VERIFYING, ITEM_STATE.BLOCKED, ITEM_STATE.FAILED]],
  [ITEM_STATE.VERIFYING, [ITEM_STATE.PDF_CACHED, ITEM_STATE.COMPLETED, ITEM_STATE.BROWSER_DOWNLOADED, ITEM_STATE.VERIFICATION_INCONCLUSIVE, ITEM_STATE.INVALID_RESPONSE, ITEM_STATE.QUARANTINED, ITEM_STATE.BLOCKED, ITEM_STATE.FAILED]],
  [ITEM_STATE.LOGIN_REQUIRED, [ITEM_STATE.RESOLVING, ITEM_STATE.BLOCKED, ITEM_STATE.ABANDONED]],
  [ITEM_STATE.MANUAL_REQUIRED, [ITEM_STATE.RESOLVING, ITEM_STATE.BLOCKED, ITEM_STATE.ABANDONED]],
  [ITEM_STATE.NO_ENTITLEMENT, [ITEM_STATE.RESOLVING, ITEM_STATE.ABANDONED]],
  [ITEM_STATE.BLOCKED, [ITEM_STATE.RESOLVING, ITEM_STATE.QUEUED, ITEM_STATE.ABANDONED, ITEM_STATE.FAILED]],
  [ITEM_STATE.FAILED, [ITEM_STATE.RESOLVING, ITEM_STATE.QUEUED, ITEM_STATE.ABANDONED]],
  [ITEM_STATE.BROWSER_DOWNLOADED, [ITEM_STATE.RESOLVING, ITEM_STATE.QUEUED, ITEM_STATE.VERIFYING]],
  [ITEM_STATE.VERIFICATION_INCONCLUSIVE, [ITEM_STATE.PDF_CACHED, ITEM_STATE.VERIFYING, ITEM_STATE.QUARANTINED, ITEM_STATE.ABANDONED, ITEM_STATE.COMPLETED]],
  [ITEM_STATE.INVALID_RESPONSE, [ITEM_STATE.RESOLVING, ITEM_STATE.QUEUED, ITEM_STATE.ABANDONED]],
  [ITEM_STATE.QUARANTINED, [ITEM_STATE.PDF_CACHED, ITEM_STATE.RESOLVING, ITEM_STATE.ABANDONED, ITEM_STATE.COMPLETED]],
  [ITEM_STATE.ABANDONED, []],
  [ITEM_STATE.COMPLETED, []],
]);

export function canTransition(from, to) {
  return Boolean(ALLOWED.get(from)?.includes(to));
}

export function transitionItem(item, nextState, patch = {}, now = new Date()) {
  if (item.state === nextState) return { ...item, ...patch, updatedAt: now.toISOString() };
  if (!canTransition(item.state, nextState)) throw new Error(`非法任务状态转换: ${item.state} -> ${nextState}`);
  return {
    ...item,
    ...patch,
    state: nextState,
    updatedAt: now.toISOString(),
    stateHistory: [...(item.stateHistory || []), { from: item.state, to: nextState, at: now.toISOString() }].slice(-40),
  };
}

export function transitionCapturedPdfToCaching(item, patch = {}, now = new Date()) {
  let current = item;
  if (isManualState(current.state)) {
    current = transitionItem(current, ITEM_STATE.RESOLVING, {}, now);
  }
  if (current.state === ITEM_STATE.RESOLVING) {
    current = transitionItem(current, ITEM_STATE.CANDIDATE_REGISTERED, {}, now);
  }
  return transitionItem(current, ITEM_STATE.CACHING, patch, now);
}

export function isManualState(state) {
  return state === ITEM_STATE.LOGIN_REQUIRED || state === ITEM_STATE.MANUAL_REQUIRED;
}

export function canAutoRetry(item) {
  return !isManualState(item.state) && Number(item.retryCount || 0) < 2;
}
